# Generated by Django 5.2 on 2025-11-29 10:54

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название иконки (для админки)')),
                ('icon_class', models.CharField(max_length=50, verbose_name="CSS класс иконки (например, 'fas fa-chart-line')")),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('research', 'Научные проекты и разработки'), ('development', 'Коммерциализационные проекты и разработки'), ('commercial', 'Коммерциализация')], default='research', max_length=20, verbose_name='Категория')),
                ('title', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес (слаг)')),
                ('tagline', models.CharField(max_length=200, verbose_name='Слоган/Краткое описание')),
                ('status_tag_1', models.CharField(blank=True, max_length=50, verbose_name='Статус (тег 1)')),
                ('status_tag_2', models.CharField(blank=True, max_length=50, verbose_name='Статус (тег 2)')),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Основной абзац описания')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка на проект')),
                ('task_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Задача проекта')),
                ('task_subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок для задачи проекта')),
                ('result_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Результаты проекта')),
                ('detailed_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name="Дополнительная информация (для кнопки 'Подробнее')")),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Ключевые слова (через запятую)')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и Фамилия')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес (слаг)')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(upload_to='team_photos/', verbose_name='Фотография')),
                ('scopus_id', models.CharField(blank=True, max_length=50, verbose_name='Scopus Author ID')),
                ('orcid_id', models.CharField(blank=True, max_length=50, verbose_name='ORCID iD')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес (слаг)')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Изображение')),
                ('category', models.CharField(help_text='Например: Исследования, Партнерство', max_length=50, verbose_name='Категория')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
                ('author_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя автора (текст)')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Ключевые слова (через запятую)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='main.project', verbose_name='Связанный проект')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст особенности')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.icon', verbose_name='Иконка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Особенность проекта',
                'verbose_name_plural': 'Особенности проекта',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_results/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись к изображению')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_images', to='main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображение результата',
                'verbose_name_plural': 'Изображения результатов',
            },
        ),
        migrations.CreateModel(
            name='ProjectTechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Название технологии')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.icon', verbose_name='Иконка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='main.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Технология стека',
                'verbose_name_plural': 'Технологический стек',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.icon', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=50, verbose_name="CSS класс иконки (например, 'fab fa-linkedin')")),
                ('url', models.URLField(verbose_name='URL-адрес ссылки')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='main.teammember')),
            ],
            options={
                'verbose_name': 'Ссылка на соцсеть',
                'verbose_name_plural': 'Ссылки на соцсети',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('source', models.CharField(max_length=200, verbose_name='Журнал или источник')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Краткое описание')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на публикацию')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='main.project', verbose_name='Связанный проект')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='main.teammember', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-publication_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='projects', to='main.teammember', verbose_name='Команда проекта'),
        ),
    ]
