# Generated by Django 5.2 on 2025-11-29 12:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='projecttechstack',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='projectfeature',
            name='icon',
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-publication_date', 'title_ru'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='detailed_info',
        ),
        migrations.RemoveField(
            model_name='project',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='result_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status_tag_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status_tag_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task_subtitle',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='projectfeature',
            name='text',
        ),
        migrations.RemoveField(
            model_name='projectresultimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='position',
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Содержание (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Содержание (KK)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Содержание (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (KK)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_info_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Доп. информация (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_info_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Доп. информация (KK)'),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_info_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Доп. информация (RU)'),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Основное описание (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Основное описание (KK)'),
        ),
        migrations.AddField(
            model_name='project',
            name='full_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Основное описание (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='result_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Результаты проекта (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_description_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Результаты проекта (KK)'),
        ),
        migrations.AddField(
            model_name='project',
            name='result_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Результаты проекта (RU)'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_tag_1_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус 1 (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_tag_1_kk',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус 1 (KK)'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_tag_1_ru',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус 1 (RU)'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_tag_2_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус 2 (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_tag_2_kk',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус 2 (KK)'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_tag_2_ru',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус 2 (RU)'),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Слоган (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Слоган (KK)'),
        ),
        migrations.AddField(
            model_name='project',
            name='tagline_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Слоган (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='task_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Задача проекта (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_description_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Задача проекта (KK)'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Задача проекта (RU)'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_subtitle_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок задачи (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_subtitle_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок задачи (KK)'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_subtitle_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок задачи (RU)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название проекта (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название проекта (KK)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(default='', max_length=100, verbose_name='Название проекта (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='icon_class',
            field=models.CharField(default='', help_text="Например: 'fas fa-chart-line'", max_length=100, verbose_name='CSS класс иконки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='text_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст особенности (EN)'),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='text_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст особенности (KK)'),
        ),
        migrations.AddField(
            model_name='projectfeature',
            name='text_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Текст особенности (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectresultimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись (EN)'),
        ),
        migrations.AddField(
            model_name='projectresultimage',
            name='caption_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись (KK)'),
        ),
        migrations.AddField(
            model_name='projectresultimage',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись (RU)'),
        ),
        migrations.AddField(
            model_name='projecttechstack',
            name='icon_class',
            field=models.CharField(default='', help_text="Например: 'fab fa-python'", max_length=100, verbose_name='CSS класс иконки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Краткое описание (KK)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Краткое описание (RU)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название статьи (EN)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_kk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название статьи (KK)'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название статьи (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Краткое описание (KK)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(default='', verbose_name='Краткое описание (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Например: 'fas fa-cogs'", max_length=100, verbose_name='CSS класс иконки'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название услуги (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название услуги (KK)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(default='', max_length=100, verbose_name='Название услуги (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Биография (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_kk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Биография (KK)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Биография (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Отображать на сайте?'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя и Фамилия (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя и Фамилия (KK)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ru',
            field=models.CharField(default='', max_length=100, verbose_name='Имя и Фамилия (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_kk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность (KK)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность (RU)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ключевые слова (SEO)'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(help_text="Например: 'fab fa-linkedin' или 'bi bi-telegram'", max_length=50, verbose_name='CSS класс иконки'),
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
